# Generated by Django 4.0 on 2022-03-20 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='Job',
        ),
    ]
